/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import twitter.excecoes.PDException;
import twitter.excecoes.PIException;
import twitter.objetos.Perfil;
import twitter.objetos.PessoaFisica;
import twitter.objetos.PessoaJuridica;
import twitter.servico.MyTwitter;

/**
 *
 * @author mtayllan
 */
public class PerfilEditar extends javax.swing.JFrame {
    
    private final String usuarioLogado;
    private final MyTwitter myTwitter;
    private Perfil perfil;
    
    public PerfilEditar(String usuarioLogado, MyTwitter myTwitter) {
        initComponents();
        this.myTwitter = myTwitter;
        this.usuarioLogado = usuarioLogado;
        preencheDados();
    }
    
    private void preencheDados(){
        try {
            perfil = myTwitter.getUsuario(usuarioLogado);
            if (perfil instanceof PessoaJuridica){
                idTextField.setText(String.valueOf(((PessoaJuridica) perfil).getCnpj()));
            }else{
                idTextField.setText(String.valueOf(((PessoaFisica) perfil).getCpf()));
            }
            chkIsAtivo.setSelected(perfil.isAtivo());
        } catch (PIException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        botaoSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chkIsAtivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 172, 237));
        setUndecorated(true);

        jLayeredPane1.setBackground(new java.awt.Color(0, 172, 237));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close_icon_24x24.png"))); // NOI18N
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSairMouseClicked(evt);
            }
        });
        jLayeredPane1.add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR PERFIL");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 310, 40));

        btnSalvar.setBackground(java.awt.Color.white);
        btnSalvar.setForeground(new java.awt.Color(0, 172, 237));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 148, 50));

        idTextField.setForeground(java.awt.Color.white);
        jLayeredPane1.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 260, -1));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("CPF/CNPJ:");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));

        chkIsAtivo.setForeground(java.awt.Color.white);
        chkIsAtivo.setText("Ativo?");
        jLayeredPane1.add(chkIsAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        setBounds(0, 0, 383, 301);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_botaoSairMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (perfil instanceof PessoaFisica){
                PessoaFisica pessoaFisica = new PessoaFisica(usuarioLogado);
                pessoaFisica.setAtivo(chkIsAtivo.isSelected());
                pessoaFisica.setCpf(Long.parseLong(idTextField.getText()));
                myTwitter.atualizarPerfil(pessoaFisica);
            }else{
                PessoaJuridica pessoaJuridica = new PessoaJuridica(usuarioLogado);
                pessoaJuridica.setAtivo(chkIsAtivo.isSelected());
                pessoaJuridica.setCnpj(Long.parseLong(idTextField.getText()));
                myTwitter.atualizarPerfil(pessoaJuridica);
            }
        } catch (PIException | PDException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkIsAtivo;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
